# -*- coding: utf-8 -*-
"""compare_models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oC2IRsRCHcOfd51mI-i7EloaeI45fxY6
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay

import matplotlib.pyplot as plt

# ======================
# LOAD DATA
# ======================

df = pd.read_csv("cardio_train.csv", sep=";")

if "id" in df.columns:
    df = df.drop(columns=["id"])

if df["age"].max() > 200:
    df["age"] = (df["age"] / 365).astype(int)

df["BMI"] = df["weight"] / ((df["height"] / 100) ** 2)

X = df[[
    "age","height","weight","BMI",
    "ap_hi","ap_lo","cholesterol","gluc"
]]

y = df["cardio"]

# ======================
# SPLIT
# ======================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ======================
# MODELS
# ======================

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=200),
    "Gradient Boosting": GradientBoostingClassifier()
}

results = []

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for ax, (name, model) in zip(axes, models.items()):

    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("model", model)
    ])

    pipe.fit(X_train, y_train)
    pred = pipe.predict(X_test)

    acc = accuracy_score(y_test, pred)
    f1 = f1_score(y_test, pred)

    results.append([name, acc, f1])

    cm = confusion_matrix(y_test, pred)
    disp = ConfusionMatrixDisplay(cm)
    disp.plot(ax=ax)

    ax.set_title(f"{name}\nAcc={acc:.2f} F1={f1:.2f}")

plt.tight_layout()
plt.show()

print(pd.DataFrame(results, columns=["Model","Accuracy","F1"]))