# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkubojQ-0LYCceUDKtsg-WwroJNMr3V2
"""

import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# ======================
# DATA LOAD
# ======================

df = pd.read_csv("cardio_train.csv", sep=";")

# удаляем id
if "id" in df.columns:
    df = df.drop(columns=["id"])

# age в годы
if df["age"].max() > 200:
    df["age"] = (df["age"] / 365).astype(int)

# ======================
# FEATURE ENGINEERING
# ======================

df["BMI"] = df["weight"] / ((df["height"] / 100) ** 2)

# ======================
# FEATURES
# ======================

X = df[[
    "age",
    "height",
    "weight",
    "BMI",
    "ap_hi",
    "ap_lo",
    "cholesterol",
    "gluc"
]]

y = df["cardio"]

# ======================
# SPLIT
# ======================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ======================
# MODEL
# ======================

model = Pipeline([
    ("scaler", StandardScaler()),
    ("rf", RandomForestClassifier(
        n_estimators=300,
        max_depth=10,
        random_state=42
    ))
])

# training
model.fit(X_train, y_train)

# evaluation
pred = model.predict(X_test)
acc = accuracy_score(y_test, pred)

print("Accuracy:", acc)

# save model
pickle.dump(model, open("model.pkl", "wb"))

print("Model saved ✔")